setup-loader
SergeiFojin/Todo-React pull request #15
Opened 2022-12-23 13:16 UTC by SergeiFojin

2022-12-23 13:20 UTC, IslamRustamov98 commented on todo-react-frontend/src/store/fetchReducer/fetchReducer.ts
> +      console.log(action.payload);
remove log

2022-12-23 13:21 UTC, IslamRustamov98 commented on todo-react-frontend/src/store/sagas/todosSaga.ts
> +  }
this should be changed to try/catch block instead of if else

2022-12-23 13:21 UTC, IslamRustamov98 commented on todo-react-frontend/src/pages/Homepage/HomePage.tsx
> +        isLoading === FetchStatusEnum.LOADING
name isLoading (prefix **is**) is implying that your variable is boolean, but in reality it's not boolean.

2022-12-26 07:09 UTC, bguchinov requested changes

2022-12-26 07:09 UTC, bguchinov commented on todo-react-frontend/src/pages/Homepage/HomePage.tsx
> +        && <ErrorMessage />
лучше перенести && на строчку выше и после обернуть компонент ( )

2022-12-26 07:09 UTC, bguchinov commented on todo-react-frontend/src/pages/TodoPage/TodoPage.tsx
> +        && <ErrorMessage />
Тут тоже

2022-12-26 07:09 UTC, bguchinov commented on todo-react-frontend/src/store/sagas/todosSaga.ts
> +    const result: Todo[] = yield call(getTasksRequest);
добавь пустую строчку над константой

2022-12-26 07:09 UTC, bguchinov commented on todo-react-frontend/src/store/sagas/todosSaga.ts
> +    const result: Todo[] = yield addTaskRequest(payload.value, payload.isCompleted);
и тут

2022-12-26 07:09 UTC, bguchinov commented on todo-react-frontend/src/components/Loader/Loader.tsx
> +
В этом компоненте не нужен return

2022-12-26 07:22 UTC, merged